# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/course-lab_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_multip_2num_0_0/design_1_multip_2num_0_0.xci
# IP: The module: 'design_1_multip_2num_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/course-lab_1/vivado/vivado.gen/sources_1/bd/design_1/ip/design_1_multip_2num_0_0/constraints/multip_2num_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_multip_2num_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ubuntu/course-lab_1/vivado/vivado.srcs/sources_1/bd/design_1/ip/design_1_multip_2num_0_0/design_1_multip_2num_0_0.xci
# IP: The module: 'design_1_multip_2num_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/course-lab_1/vivado/vivado.gen/sources_1/bd/design_1/ip/design_1_multip_2num_0_0/constraints/multip_2num_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_multip_2num_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
